image: Visual Studio 2019

environment:
  PYTHON: "C:\\Python39"
  matrix:
  - TOXENV: py36
  - TOXENV: py39

build: off

install:
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
- python -m pip install tox

test_script:
- tox
